name: Update Prompt from Portfolio

on:
  schedule:
    - cron: '0 3 * * 0' # Sunday at 3:00 UTC
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  crawl_and_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false --local

      - name: Install dependencies (including Playwright browsers)
        working-directory: ./backend
        run: |
          poetry install --no-root
          poetry run playwright install --with-deps chromium # Install browser & OS dependencies

      - name: Run crawl and patch script
        working-directory: ./backend
        env:
          PORTFOLIO_URL: ${{ secrets.PORTFOLIO_URL }} # From GitHub Secrets
          CHATBOT_HOST: ${{ secrets.CHATBOT_HOST }}   # From GitHub Secrets

        run: poetry run python tools/crawl_and_patch.py 