name: Update Prompt from Portfolio

on:
  schedule:
    # Run once a day at 3:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  crawl_and_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false --local

      - name: Install dependencies (including Playwright browsers)
        run: |
          poetry install
          poetry run playwright install --with-deps chromium # Install browser & OS dependencies

      - name: Run crawl and patch script
        env:
          PORTFOLIO_URL: ${{ secrets.PORTFOLIO_URL }} # From GitHub Secrets
          CHATBOT_HOST: ${{ secrets.CHATBOT_HOST }}   # From GitHub Secrets
          # GOOGLE_API_KEY is not directly needed by the script itself
        run: poetry run python backend/tools/crawl_and_patch.py 